// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/function/scalar/generic/alias.cpp>
#include </Users/carlo/duckdb/src/function/scalar/generic/constant_or_null.cpp>
#include </Users/carlo/duckdb/src/function/scalar/generic/current_setting.cpp>
#include </Users/carlo/duckdb/src/function/scalar/generic/hash.cpp>
#include </Users/carlo/duckdb/src/function/scalar/generic/least.cpp>
#include </Users/carlo/duckdb/src/function/scalar/generic/stats.cpp>
#include </Users/carlo/duckdb/src/function/scalar/generic/typeof.cpp>
