// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/optimizer/statistics/operator/propagate_aggregate.cpp>
#include </Users/carlo/duckdb/src/optimizer/statistics/operator/propagate_cross_product.cpp>
#include </Users/carlo/duckdb/src/optimizer/statistics/operator/propagate_filter.cpp>
#include </Users/carlo/duckdb/src/optimizer/statistics/operator/propagate_get.cpp>
#include </Users/carlo/duckdb/src/optimizer/statistics/operator/propagate_limit.cpp>
#include </Users/carlo/duckdb/src/optimizer/statistics/operator/propagate_join.cpp>
#include </Users/carlo/duckdb/src/optimizer/statistics/operator/propagate_order.cpp>
#include </Users/carlo/duckdb/src/optimizer/statistics/operator/propagate_projection.cpp>
#include </Users/carlo/duckdb/src/optimizer/statistics/operator/propagate_set_operation.cpp>
#include </Users/carlo/duckdb/src/optimizer/statistics/operator/propagate_window.cpp>
