// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/optimizer/pushdown/pushdown_aggregate.cpp>
#include </Users/carlo/duckdb/src/optimizer/pushdown/pushdown_cross_product.cpp>
#include </Users/carlo/duckdb/src/optimizer/pushdown/pushdown_filter.cpp>
#include </Users/carlo/duckdb/src/optimizer/pushdown/pushdown_get.cpp>
#include </Users/carlo/duckdb/src/optimizer/pushdown/pushdown_inner_join.cpp>
#include </Users/carlo/duckdb/src/optimizer/pushdown/pushdown_limit.cpp>
#include </Users/carlo/duckdb/src/optimizer/pushdown/pushdown_left_join.cpp>
#include </Users/carlo/duckdb/src/optimizer/pushdown/pushdown_mark_join.cpp>
#include </Users/carlo/duckdb/src/optimizer/pushdown/pushdown_projection.cpp>
#include </Users/carlo/duckdb/src/optimizer/pushdown/pushdown_set_operation.cpp>
#include </Users/carlo/duckdb/src/optimizer/pushdown/pushdown_single_join.cpp>
