// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/storage/metadata/metadata_manager.cpp>
#include </Users/carlo/duckdb/src/storage/metadata/metadata_reader.cpp>
#include </Users/carlo/duckdb/src/storage/metadata/metadata_writer.cpp>
