// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/storage/serialization/serialize_constraint.cpp>
#include </Users/carlo/duckdb/src/storage/serialization/serialize_create_info.cpp>
#include </Users/carlo/duckdb/src/storage/serialization/serialize_expression.cpp>
#include </Users/carlo/duckdb/src/storage/serialization/serialize_logical_operator.cpp>
#include </Users/carlo/duckdb/src/storage/serialization/serialize_macro_function.cpp>
#include </Users/carlo/duckdb/src/storage/serialization/serialize_nodes.cpp>
#include </Users/carlo/duckdb/src/storage/serialization/serialize_parsed_expression.cpp>
#include </Users/carlo/duckdb/src/storage/serialization/serialize_parse_info.cpp>
#include </Users/carlo/duckdb/src/storage/serialization/serialize_query_node.cpp>
#include </Users/carlo/duckdb/src/storage/serialization/serialize_result_modifier.cpp>
#include </Users/carlo/duckdb/src/storage/serialization/serialize_statement.cpp>
#include </Users/carlo/duckdb/src/storage/serialization/serialize_table_filter.cpp>
#include </Users/carlo/duckdb/src/storage/serialization/serialize_tableref.cpp>
#include </Users/carlo/duckdb/src/storage/serialization/serialize_types.cpp>
#include </Users/carlo/duckdb/src/storage/serialization/serialize_storage.cpp>
