// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/storage/buffer/buffer_handle.cpp>
#include </Users/carlo/duckdb/src/storage/buffer/block_handle.cpp>
#include </Users/carlo/duckdb/src/storage/buffer/block_manager.cpp>
#include </Users/carlo/duckdb/src/storage/buffer/buffer_pool.cpp>
#include </Users/carlo/duckdb/src/storage/buffer/buffer_pool_reservation.cpp>
