// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/function/scalar/math/numeric.cpp>
#include </Users/carlo/duckdb/src/function/scalar/math/random.cpp>
#include </Users/carlo/duckdb/src/function/scalar/math/setseed.cpp>
