// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/common/arrow/appender/bool_data.cpp>
#include </Users/carlo/duckdb/src/common/arrow/appender/list_data.cpp>
#include </Users/carlo/duckdb/src/common/arrow/appender/map_data.cpp>
#include </Users/carlo/duckdb/src/common/arrow/appender/struct_data.cpp>
#include </Users/carlo/duckdb/src/common/arrow/appender/union_data.cpp>
