// copy of duckdb_type, with names shortened
export enum DuckDBTypeId {
  INVALID = 0,
  BOOLEAN = 1,
  TINYINT = 2,
  SMALLINT = 3,
  INTEGER = 4,
  BIGINT = 5,
  UTINYINT = 6,
  USMALLINT = 7,
  UINTEGER = 8,
  UBIGINT = 9,
  FLOAT = 10,
  DOUBLE = 11,
  TIMESTAMP = 12,
  DATE = 13,
  TIME = 14,
  INTERVAL = 15,
  HUGEINT = 16,
  UHUGEINT = 17,
  VARCHAR = 18,
  BLOB = 19,
  DECIMAL = 20,
  TIMESTAMP_S = 21,
  TIMESTAMP_MS = 22,
  TIMESTAMP_NS = 23,
  ENUM = 24,
  LIST = 25,
  STRUCT = 26,
  MAP = 27,
  UUID = 28,
  UNION = 29,
  BIT = 30,
  TIME_TZ = 31,
  TIMESTAMP_TZ = 32,
}
