// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/function/scalar/date/age.cpp>
#include </Users/carlo/duckdb/src/function/scalar/date/current.cpp>
#include </Users/carlo/duckdb/src/function/scalar/date/epoch.cpp>
#include </Users/carlo/duckdb/src/function/scalar/date/date_diff.cpp>
#include </Users/carlo/duckdb/src/function/scalar/date/date_part.cpp>
#include </Users/carlo/duckdb/src/function/scalar/date/date_sub.cpp>
#include </Users/carlo/duckdb/src/function/scalar/date/date_trunc.cpp>
#include </Users/carlo/duckdb/src/function/scalar/date/make_date.cpp>
#include </Users/carlo/duckdb/src/function/scalar/date/strftime.cpp>
#include </Users/carlo/duckdb/src/function/scalar/date/time_bucket.cpp>
#include </Users/carlo/duckdb/src/function/scalar/date/to_interval.cpp>
