// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/common/adbc/nanoarrow/metadata.cpp>
#include </Users/carlo/duckdb/src/common/adbc/nanoarrow/schema.cpp>
#include </Users/carlo/duckdb/src/common/adbc/nanoarrow/allocator.cpp>
#include </Users/carlo/duckdb/src/common/adbc/nanoarrow/single_batch_array_stream.cpp>
