// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/catalog/default/default_functions.cpp>
#include </Users/carlo/duckdb/src/catalog/default/default_schemas.cpp>
#include </Users/carlo/duckdb/src/catalog/default/default_types.cpp>
#include </Users/carlo/duckdb/src/catalog/default/default_views.cpp>
