// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/function/scalar/operators/add.cpp>
#include </Users/carlo/duckdb/src/function/scalar/operators/arithmetic.cpp>
#include </Users/carlo/duckdb/src/function/scalar/operators/bitwise.cpp>
#include </Users/carlo/duckdb/src/function/scalar/operators/multiply.cpp>
#include </Users/carlo/duckdb/src/function/scalar/operators/subtract.cpp>
