// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/core_functions/aggregate/algebraic/avg.cpp>
#include </Users/carlo/duckdb/src/core_functions/aggregate/algebraic/covar.cpp>
#include </Users/carlo/duckdb/src/core_functions/aggregate/algebraic/stddev.cpp>
#include </Users/carlo/duckdb/src/core_functions/aggregate/algebraic/corr.cpp>
