// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/core_functions/scalar/list/array_slice.cpp>
#include </Users/carlo/duckdb/src/core_functions/scalar/list/flatten.cpp>
#include </Users/carlo/duckdb/src/core_functions/scalar/list/list_aggregates.cpp>
#include </Users/carlo/duckdb/src/core_functions/scalar/list/list_lambdas.cpp>
#include </Users/carlo/duckdb/src/core_functions/scalar/list/list_value.cpp>
#include </Users/carlo/duckdb/src/core_functions/scalar/list/list_sort.cpp>
#include </Users/carlo/duckdb/src/core_functions/scalar/list/list_distance.cpp>
#include </Users/carlo/duckdb/src/core_functions/scalar/list/list_cosine_similarity.cpp>
#include </Users/carlo/duckdb/src/core_functions/scalar/list/list_inner_product.cpp>
#include </Users/carlo/duckdb/src/core_functions/scalar/list/range.cpp>
