// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/core_functions/scalar/generic/alias.cpp>
#include </Users/carlo/duckdb/src/core_functions/scalar/generic/current_setting.cpp>
#include </Users/carlo/duckdb/src/core_functions/scalar/generic/error.cpp>
#include </Users/carlo/duckdb/src/core_functions/scalar/generic/hash.cpp>
#include </Users/carlo/duckdb/src/core_functions/scalar/generic/least.cpp>
#include </Users/carlo/duckdb/src/core_functions/scalar/generic/stats.cpp>
#include </Users/carlo/duckdb/src/core_functions/scalar/generic/typeof.cpp>
#include </Users/carlo/duckdb/src/core_functions/scalar/generic/system_functions.cpp>
