// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/function/scalar/string/caseconvert.cpp>
#include </Users/carlo/duckdb/src/function/scalar/string/concat.cpp>
#include </Users/carlo/duckdb/src/function/scalar/string/length.cpp>
#include </Users/carlo/duckdb/src/function/scalar/string/like.cpp>
#include </Users/carlo/duckdb/src/function/scalar/string/nfc_normalize.cpp>
#include </Users/carlo/duckdb/src/function/scalar/string/regexp.cpp>
#include </Users/carlo/duckdb/src/function/scalar/string/substring.cpp>
#include </Users/carlo/duckdb/src/function/scalar/string/prefix.cpp>
#include </Users/carlo/duckdb/src/function/scalar/string/strip_accents.cpp>
#include </Users/carlo/duckdb/src/function/scalar/string/suffix.cpp>
#include </Users/carlo/duckdb/src/function/scalar/string/contains.cpp>
