// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/execution/operator/persistent/csv_rejects_table.cpp>
#include </Users/carlo/duckdb/src/execution/operator/persistent/physical_fixed_batch_copy.cpp>
#include </Users/carlo/duckdb/src/execution/operator/persistent/physical_batch_copy_to_file.cpp>
#include </Users/carlo/duckdb/src/execution/operator/persistent/physical_batch_insert.cpp>
#include </Users/carlo/duckdb/src/execution/operator/persistent/physical_copy_to_file.cpp>
#include </Users/carlo/duckdb/src/execution/operator/persistent/physical_delete.cpp>
#include </Users/carlo/duckdb/src/execution/operator/persistent/physical_export.cpp>
#include </Users/carlo/duckdb/src/execution/operator/persistent/physical_insert.cpp>
#include </Users/carlo/duckdb/src/execution/operator/persistent/physical_update.cpp>
