// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/function/built_in_functions.cpp>
#include </Users/carlo/duckdb/src/function/cast_rules.cpp>
#include </Users/carlo/duckdb/src/function/compression_config.cpp>
#include </Users/carlo/duckdb/src/function/function.cpp>
#include </Users/carlo/duckdb/src/function/function_binder.cpp>
#include </Users/carlo/duckdb/src/function/function_set.cpp>
#include </Users/carlo/duckdb/src/function/pragma_function.cpp>
#include </Users/carlo/duckdb/src/function/macro_function.cpp>
#include </Users/carlo/duckdb/src/function/scalar_macro_function.cpp>
#include </Users/carlo/duckdb/src/function/table_macro_function.cpp>
#include </Users/carlo/duckdb/src/function/scalar_function.cpp>
#include </Users/carlo/duckdb/src/function/table_function.cpp>
#include </Users/carlo/duckdb/src/function/udf_function.cpp>
