// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/transaction/duck_transaction_manager.cpp>
#include </Users/carlo/duckdb/src/transaction/duck_transaction.cpp>
#include </Users/carlo/duckdb/src/transaction/meta_transaction.cpp>
#include </Users/carlo/duckdb/src/transaction/undo_buffer.cpp>
#include </Users/carlo/duckdb/src/transaction/transaction_context.cpp>
#include </Users/carlo/duckdb/src/transaction/transaction.cpp>
#include </Users/carlo/duckdb/src/transaction/transaction_manager.cpp>
#include </Users/carlo/duckdb/src/transaction/commit_state.cpp>
#include </Users/carlo/duckdb/src/transaction/rollback_state.cpp>
#include </Users/carlo/duckdb/src/transaction/cleanup_state.cpp>
