// Unity Build generated by CMake
#include </Users/carlo/duckdb/src/function/scalar/union/union_extract.cpp>
#include </Users/carlo/duckdb/src/function/scalar/union/union_tag.cpp>
#include </Users/carlo/duckdb/src/function/scalar/union/union_value.cpp>
